import black_tap from "../Assets/black-tap.png";
import gold_tap from "../Assets/gold-tap.png";
import chair_2 from "../Assets/chair_2.png";
import chair_1 from "../Assets/chair_1.png";
import white_tap from "../Assets/white-tap.png";
import chair_3 from "../Assets/chair_3.png";

const Products_List = [
  {
    id: 1,
    productImg: black_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "sanitary wares",
  },
  {
    id: 2,
    productImg: gold_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "sanitary wares",
  },
  {
    id: 3,
    productImg: chair_1,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "sanitary wares",
  },
  {
    id: 4,
    productImg: white_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "sanitary wares",
  },
  {
    id: 5,
    productImg: chair_2,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "doors",
  },
  {
    id: 6,
    productImg: chair_3,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "doors",
  },
  {
    id: 7,
    productImg: gold_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "doors",
  },
  {
    id: 8,
    productImg: chair_1,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "doors",
  },
  {
    id: 9,
    productImg: white_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "doors",
  },
  {
    id: 10,
    productImg: chair_2,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "doors",
  },
  {
    id: 11,
    productImg: chair_3,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "doors",
  },
  {
    id: 12,
    productImg: gold_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "doors",
  },
  {
    id: 13,
    productImg: white_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "building materials",
  },
  {
    id: 14,
    productImg: chair_2,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "building materials",
  },
  {
    id: 15,
    productImg: chair_1,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "building materials",
  },
  {
    id: 16,
    productImg: white_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "building materials",
  },
  {
    id: 17,
    productImg: chair_3,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "building materials",
  },
  {
    id: 18,
    productImg: gold_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "building materials",
  },
  {
    id: 19,
    productImg: black_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "building materials",
  },
  {
    id: 20,
    productImg: gold_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "funitures",
  },
  {
    id: 21,
    productImg: chair_1,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "funitures",
  },
  {
    id: 22,
    productImg: white_tap,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "funitures",
  },
  {
    id: 23,
    productImg: chair_2,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "funtiures",
  },
  {
    id: 24,
    productImg: chair_3,
    productName: "Product name",
    code: "MMSWIIX3I",
    price: 8500,
    category: "funitures",
  },
];

export default Products_List;
